app:
  name: Agent
  version: 1.0.0
  environment: development
  title: Fehmi Agent
  tooltip: "Fehmi Unified Endpoint Agent\nVersion: 1.0.0"
  dimension:
    width: 500
    height: 500
  tray:
    - id: 0
      title: Dashboard
      tooltip: Show Dashboard view
    - sperator: true
    - id: 1
      title: Scan
      tooltip: Run Scanner
    - id: 2
      title: Connect
      tooltip: Connect to Server
    - sperator: true
    - id: 100
      title: Quit
      tooltip: Quit the application

server:
  - tag: primary
    type: local
    ip: 10.10.10.5
    fqdn: uem.shalimar.local
    domain: shalimar.local
    port: 3307

database:
  - tag: primary
    engine: mongos
    host: 100.100.100.5
    port: 27017
    user: admin
    password: supersecret
    name: test-db